qdrant:
  host: localhost
  port: 6334 # gRPC port, not HTTP
  collection: pokemon_docs

ollama:
  base_url: http://localhost:11434
  model: qwen2.5-coder:3b
  embedding_model: nomic-embed-text

http_server:
  port: 8080
